- hosts: localhost
  connection: local
 
  vars:
    homebrew_taps:
      - caskroom/cask
 
    homebrew_cask_packages:
      - name: virtualbox
      - name: google-chrome
      - name: firefox
      - name: slack
      - name: visual-studio-code
 
    homebrew_packages:
      - name: ansible
      - name: git
      - name: tig
      - name: zsh
      - name: nodebrew
      - name: rbenv
 
  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes
 
    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'
 
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
 
    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: create nodebrew directory
      file: path=~/.nodebrew/src state=directory

    - name: install latest nodejs
      command: nodebrew install-binary latest